services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: yamhamelach
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: matches_db
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
